<script setup>
import { computed, onMounted, ref } from 'vue'
import { supabase } from '../lib/supabase'

const props=defineProps({launchToken:{type:String,required:true},lang:{type:String,default:'uk'}})
const words={
 uk:{panel:'Адмін-панель',secure:'Захищений доступ',refresh:'Оновити',overview:'Огляд',orders:'Замовлення',products:'Товари',expenses:'Витрати',revenue:'Дохід',cost:'Собівартість',other:'Інші витрати',profit:'Чистий прибуток',allOrders:'Усього замовлень',newOrders:'Нові',lowStock:'Закінчуються',recent:'Останні замовлення',noOrders:'Замовлень ще немає',customer:'Покупець',date:'Дата',amount:'Сума',status:'Статус',delivery:'Доставка',comment:'Коментар',items:'Склад замовлення',save:'Зберегти',addProduct:'Додати товар',edit:'Редагувати',remove:'Видалити',search:'Пошук товару',name:'Назва',brand:'Виробник',category:'Категорія',sellPrice:'Ціна продажу',costPrice:'Собівартість',stock:'Залишок',active:'Активний товар',specs:'Характеристики JSON',cancel:'Скасувати',addExpense:'Додати витрату',expenseTitle:'Назва витрати',expenseDate:'Дата витрати',empty:'Поки порожньо',accessDenied:'Доступ заборонено. Відкрийте панель кнопкою Telegram-бота.',confirmDelete:'Видалити цей товар з каталогу?',confirmExpense:'Видалити запис витрати?',saving:'Збереження…'},
 ru:{panel:'Админ-панель',secure:'Защищённый доступ',refresh:'Обновить',overview:'Обзор',orders:'Заказы',products:'Товары',expenses:'Расходы',revenue:'Доход',cost:'Себестоимость',other:'Другие расходы',profit:'Чистая прибыль',allOrders:'Всего заказов',newOrders:'Новые',lowStock:'Заканчиваются',recent:'Последние заказы',noOrders:'Заказов пока нет',customer:'Покупатель',date:'Дата',amount:'Сумма',status:'Статус',delivery:'Доставка',comment:'Комментарий',items:'Состав заказа',save:'Сохранить',addProduct:'Добавить товар',edit:'Редактировать',remove:'Удалить',search:'Поиск товара',name:'Название',brand:'Производитель',category:'Категория',sellPrice:'Цена продажи',costPrice:'Себестоимость',stock:'Остаток',active:'Активный товар',specs:'Характеристики JSON',cancel:'Отмена',addExpense:'Добавить расход',expenseTitle:'Название расхода',expenseDate:'Дата расхода',empty:'Пока пусто',accessDenied:'Доступ запрещён. Откройте панель кнопкой Telegram-бота.',confirmDelete:'Удалить этот товар из каталога?',confirmExpense:'Удалить запись расхода?',saving:'Сохранение…'},
 en:{panel:'Admin panel',secure:'Secure access',refresh:'Refresh',overview:'Overview',orders:'Orders',products:'Products',expenses:'Expenses',revenue:'Revenue',cost:'Product cost',other:'Other expenses',profit:'Net profit',allOrders:'Total orders',newOrders:'New',lowStock:'Low stock',recent:'Recent orders',noOrders:'No orders yet',customer:'Customer',date:'Date',amount:'Amount',status:'Status',delivery:'Delivery',comment:'Comment',items:'Order items',save:'Save',addProduct:'Add product',edit:'Edit',remove:'Remove',search:'Search products',name:'Name',brand:'Manufacturer',category:'Category',sellPrice:'Sale price',costPrice:'Cost price',stock:'Stock',active:'Active product',specs:'Specifications JSON',cancel:'Cancel',addExpense:'Add expense',expenseTitle:'Expense title',expenseDate:'Expense date',empty:'Nothing here yet',accessDenied:'Access denied. Open this panel from the Telegram bot button.',confirmDelete:'Remove this product from the catalog?',confirmExpense:'Delete this expense?',saving:'Saving…'}
}
const t=computed(()=>words[props.lang]||words.uk),lang=computed(()=>props.lang),tab=ref('overview'),loading=ref(true),busy=ref(false),error=ref(''),data=ref({metrics:{},orders:[],products:[],expenses_list:[]}),query=ref(''),expanded=ref(null),productModal=ref(false)
const blank=()=>({id:null,name:'',name_uk:'',name_ru:'',name_en:'',description:'',description_uk:'',description_ru:'',description_en:'',manufacturer:'',category_key:'cpu',price:0,cost_price:0,stock:0,active:true,specs:{}})
const productForm=ref(blank()),specsText=ref('{}'),expense=ref({title:'',amount:'',expense_date:new Date().toISOString().slice(0,10),comment:''})
const statuses=['new','confirmed','processing','shipped','completed','cancelled'],cats=['cpu','gpu','ram','storage','motherboard','psu']
const statusNames={uk:{new:'Нове',confirmed:'Підтверджено',processing:'В обробці',shipped:'Відправлено',completed:'Виконано',cancelled:'Скасовано'},ru:{new:'Новый',confirmed:'Подтверждён',processing:'В обработке',shipped:'Отправлен',completed:'Выполнен',cancelled:'Отменён'},en:{new:'New',confirmed:'Confirmed',processing:'Processing',shipped:'Shipped',completed:'Completed',cancelled:'Cancelled'}}
const filtered=computed(()=>{const q=query.value.toLowerCase();return data.value.products.filter(p=>!q||`${p.name} ${p.manufacturer} ${p.id}`.toLowerCase().includes(q))})
const currency=v=>new Intl.NumberFormat(props.lang==='en'?'en-US':props.lang==='ru'?'ru-RU':'uk-UA',{maximumFractionDigits:2}).format(Number(v||0))+' ₴'
const when=v=>new Intl.DateTimeFormat(props.lang==='en'?'en-GB':props.lang==='ru'?'ru-RU':'uk-UA',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))
const profit=computed(()=>Number(data.value.metrics.revenue||0)-Number(data.value.metrics.product_cost||0)-Number(data.value.metrics.expenses||0))
async function call(name,args={}){const r=await supabase.rpc(name,{p_launch_token:props.launchToken,...args});if(r.error)throw new Error(r.error.message);return r.data}
async function load(){loading.value=true;error.value='';try{data.value=await call('admin_get_dashboard')}catch(e){error.value=e.message.includes('Admin')?t.value.accessDenied:e.message}finally{loading.value=false}}
function editProduct(p=null){productForm.value=p?JSON.parse(JSON.stringify(p)):blank();specsText.value=JSON.stringify(productForm.value.specs||{},null,2);productModal.value=true}
async function saveProduct(){busy.value=true;error.value='';try{productForm.value.name=productForm.value.name_en||productForm.value.name_uk;productForm.value.description=productForm.value.description_en||productForm.value.description_uk||'';productForm.value.specs=JSON.parse(specsText.value||'{}');await call('admin_save_product',{p_product:productForm.value});productModal.value=false;await load()}catch(e){error.value=e.message}finally{busy.value=false}}
async function archive(p){if(!confirm(t.value.confirmDelete))return;try{await call('admin_archive_product',{p_product_id:p.id});await load()}catch(e){error.value=e.message}}
async function setStatus(o){try{await call('admin_update_order_status',{p_order_id:o.id,p_status:o.status});await load()}catch(e){error.value=e.message}}
async function addExpense(){busy.value=true;try{await call('admin_add_expense',{p_expense:{...expense.value,amount:Number(expense.value.amount)}});expense.value={title:'',amount:'',expense_date:new Date().toISOString().slice(0,10),comment:''};await load()}catch(e){error.value=e.message}finally{busy.value=false}}
async function deleteExpense(e){if(!confirm(t.value.confirmExpense))return;try{await call('admin_delete_expense',{p_expense_id:e.id});await load()}catch(x){error.value=x.message}}
onMounted(load)
</script>

<template><div class="adminApp"><header class="adminHeader"><div><i>E</i><span><b>ENDER ADMIN</b><small>{{t.secure}} · ID 631516090</small></span></div><button @click="load"><span>↻</span><em>{{t.refresh}}</em></button></header>
<div v-if="loading" class="adminState">{{t.refresh}}…</div><div v-else-if="error&& !data.orders.length" class="adminDenied"><b>⛔</b><h2>{{t.panel}}</h2><p>{{error}}</p></div>
<template v-else><nav class="adminNav"><button v-for="x in ['overview','orders','products','expenses']" :key="x" :class="{active:tab===x}" @click="tab=x">{{t[x]}}</button></nav><p v-if="error" class="adminError">{{error}}</p>
<main class="adminMain"><section v-if="tab==='overview'"><div class="adminTitle"><div><small>ENDER MARKET</small><h1>{{t.panel}}</h1></div></div><div class="metrics"><article><small>{{t.revenue}}</small><b>{{currency(data.metrics.revenue)}}</b></article><article><small>{{t.cost}}</small><b>{{currency(data.metrics.product_cost)}}</b></article><article><small>{{t.other}}</small><b>{{currency(data.metrics.expenses)}}</b></article><article class="profit"><small>{{t.profit}}</small><b>{{currency(profit)}}</b></article><article><small>{{t.allOrders}}</small><b>{{data.metrics.orders}}</b></article><article><small>{{t.newOrders}}</small><b>{{data.metrics.new_orders}}</b></article><article><small>{{t.lowStock}}</small><b>{{data.metrics.low_stock}}</b></article></div><h2>{{t.recent}}</h2><div class="orderList"><article v-for="o in data.orders.slice(0,5)" :key="o.id" class="miniOrder"><span><b>#{{o.id}} · {{o.customer_name}}</b><small>{{when(o.created_at)}} · {{statusNames[lang]?.[o.status]||o.status}}</small></span><strong>{{currency(o.total)}}</strong></article><p v-if="!data.orders.length" class="adminState">{{t.noOrders}}</p></div></section>
<section v-if="tab==='orders'"><div class="adminTitle"><h1>{{t.orders}}</h1><b>{{data.orders.length}}</b></div><div v-if="!data.orders.length" class="adminState">{{t.noOrders}}</div><article v-for="o in data.orders" :key="o.id" class="adminOrder"><button class="orderHead" @click="expanded=expanded===o.id?null:o.id"><span><b>#{{o.id}} · {{o.customer_name}}</b><small>{{when(o.created_at)}} · Telegram ID {{o.telegram_id}}</small></span><strong>{{currency(o.total)}}⌄</strong></button><div class="orderControls"><select v-model="o.status" :class="'status '+o.status" @change="setStatus(o)"><option v-for="s in statuses" :key="s" :value="s">{{statusNames[lang]?.[s]||s}}</option></select><a :href="'tel:'+o.phone">{{o.phone}}</a></div><div v-if="expanded===o.id" class="orderDetails"><p><b>{{t.delivery}}:</b> {{o.delivery_method}} · {{o.address||'—'}}</p><p v-if="o.comment"><b>{{t.comment}}:</b> {{o.comment}}</p><h3>{{t.items}}</h3><div v-for="i in o.items" :key="i.id"><span>{{i.name}} × {{i.quantity}}</span><b>{{currency(i.price*i.quantity)}}</b></div></div></article></section>
<section v-if="tab==='products'"><div class="adminTitle"><h1>{{t.products}}</h1><button class="adminPrimary" @click="editProduct()">+ {{t.addProduct}}</button></div><input v-model="query" class="adminSearch" :placeholder="t.search"><div class="productTable"><article v-for="p in filtered" :key="p.id" :class="{inactive:!p.active}"><div><small>#{{p.id}} · {{p.category_key}}</small><b>{{p.name}}</b><span>{{p.manufacturer}} · {{currency(p.price)}} · {{p.stock}} шт.</span></div><button @click="editProduct(p)">✎ {{t.edit}}</button><button class="danger" @click="archive(p)">× {{t.remove}}</button></article></div></section>
<section v-if="tab==='expenses'"><div class="adminTitle"><h1>{{t.expenses}}</h1></div><form class="expenseForm" @submit.prevent="addExpense"><input v-model.trim="expense.title" required minlength="2" :placeholder="t.expenseTitle"><input v-model.number="expense.amount" required min="0.01" step="0.01" type="number" :placeholder="t.amount"><input v-model="expense.expense_date" required type="date"><input v-model.trim="expense.comment" :placeholder="t.comment"><button class="adminPrimary" :disabled="busy">+ {{t.addExpense}}</button></form><div class="expenseList"><article v-for="e in data.expenses_list" :key="e.id"><div><b>{{e.title}}</b><small>{{e.expense_date}} · {{e.comment}}</small></div><strong>{{currency(e.amount)}}</strong><button class="danger" @click="deleteExpense(e)">×</button></article><p v-if="!data.expenses_list.length" class="adminState">{{t.empty}}</p></div></section></main></template>
<div v-if="productModal" class="adminOverlay" @click.self="productModal=false"><form class="productEditor" @submit.prevent="saveProduct"><div class="editorHead"><h2>{{productForm.id?t.edit:t.addProduct}}</h2><button type="button" @click="productModal=false">×</button></div><div class="editorGrid"><label>{{t.name}} UK<input v-model.trim="productForm.name_uk" required></label><label>{{t.name}} RU<input v-model.trim="productForm.name_ru" required></label><label>{{t.name}} EN<input v-model.trim="productForm.name_en" required></label><label>{{t.brand}}<input v-model.trim="productForm.manufacturer" required></label><label>{{t.category}}<select v-model="productForm.category_key"><option v-for="c in cats" :key="c">{{c}}</option></select></label><label>{{t.sellPrice}}<input v-model.number="productForm.price" type="number" min="0" step="0.01" required></label><label>{{t.costPrice}}<input v-model.number="productForm.cost_price" type="number" min="0" step="0.01" required></label><label>{{t.stock}}<input v-model.number="productForm.stock" type="number" min="0" required></label></div><label class="wide">{{t.specs}}<textarea v-model="specsText" rows="7"></textarea></label><label class="adminCheck"><input v-model="productForm.active" type="checkbox"> {{t.active}}</label><div class="editorActions"><button type="button" @click="productModal=false">{{t.cancel}}</button><button class="adminPrimary" :disabled="busy">{{busy?t.saving:t.save}}</button></div></form></div></div></template>
