<script setup>
import { computed, onMounted, ref } from 'vue'
import { supabase } from './lib/supabase'
const tg=window.Telegram?.WebApp;tg?.ready();tg?.expand()
const products=ref([]),loading=ref(true),error=ref(''),category=ref('Усі'),cart=ref(new Map(JSON.parse(localStorage.getItem('ender-cart')||'[]'))),cartOpen=ref(false),checkoutOpen=ref(false),submitting=ref(false),success=ref(null)
const form=ref({customer_name:'',phone:'',delivery_method:'nova_poshta',address:'',comment:''})
const categories=computed(()=>['Усі',...new Set(products.value.map(p=>p.category))]),visible=computed(()=>category.value==='Усі'?products.value:products.value.filter(p=>p.category===category.value)),lines=computed(()=>[...cart.value].map(([id,quantity])=>({product:products.value.find(p=>p.id===Number(id)),quantity})).filter(x=>x.product)),count=computed(()=>lines.value.reduce((s,x)=>s+x.quantity,0)),total=computed(()=>lines.value.reduce((s,x)=>s+Number(x.product.price)*x.quantity,0))
const money=v=>new Intl.NumberFormat('uk-UA').format(Number(v))+' грн'
function save(){localStorage.setItem('ender-cart',JSON.stringify([...cart.value]));cart.value=new Map(cart.value)}
function add(p){const k=String(p.id);cart.value.set(k,Math.min((cart.value.get(k)||0)+1,p.stock));save();tg?.HapticFeedback?.impactOccurred('light')}
function qty(p,d){const k=String(p.id),n=Math.min((cart.value.get(k)||0)+d,p.stock);n>0?cart.value.set(k,n):cart.value.delete(k);save()}
async function load(){loading.value=true;const r=await supabase.from('products').select('id,name,category,description,price,stock,image_url').eq('active',true).order('category').order('id');loading.value=false;r.error?error.value='Не вдалося завантажити каталог':products.value=r.data}
async function order(){error.value='';if(!tg?.initData&&!import.meta.env.DEV){error.value='Відкрийте магазин через Telegram-бота';return}submitting.value=true;const payload={...form.value,items:lines.value.map(x=>({product_id:x.product.id,quantity:x.quantity}))};const r=await supabase.rpc('create_telegram_order',{p_init_data:tg?.initData||'',p_payload:payload});submitting.value=false;if(r.error){error.value=r.error.message;return}success.value=r.data;cart.value.clear();save();checkoutOpen.value=false;await load()}
onMounted(load)
</script>
<template><div class="app">
<header><div class="brand"><i>E</i><div><b>ENDER MARKET</b><small>PC COMPONENTS</small></div></div><button class="cartBtn" @click="cartOpen=true">🛒 <span>{{count}}</span></button></header>
<main><section class="hero"><div class="grid"></div><small class="overline">КОМПЛЕКТУЮЧІ · ГАРАНТІЯ · ПІДТРИМКА</small><h1>Збери ПК,<br><em>який вражає.</em></h1><p>Оригінальні компоненти, чесні характеристики та допомога з підбором.</p><a href="#catalog">ДИВИТИСЯ КАТАЛОГ ↓</a><div class="stats"><div><b>100%</b><small>ОРИГІНАЛ</small></div><div><b>24/7</b><small>ЗАМОВЛЕННЯ</small></div><div><b>14</b><small>ДНІВ НА ОБМІН</small></div></div></section>
<section id="catalog" class="catalog"><div class="sectionTitle"><div><small>ОБЕРИ СВОЄ</small><h2>Каталог компонентів</h2></div><span>{{products.length}} товарів</span></div><nav><button v-for="c in categories" :key="c" :class="{active:category===c}" @click="category=c">{{c}}</button></nav><div v-if="loading" class="state">Завантаження…</div><div v-else-if="error&&!products.length" class="state error">{{error}}</div><div v-else class="products"><article v-for="p in visible" :key="p.id"><div class="photo"><img :src="p.image_url" :alt="p.name"><span>{{p.stock?'В НАЯВНОСТІ':'НЕМАЄ'}}</span></div><div class="info"><small>{{p.category}}</small><h3>{{p.name}}</h3><p>{{p.description}}</p><div class="price"><b>{{money(p.price)}}</b><button @click="add(p)" :disabled="!p.stock">+</button></div></div></article></div></section></main>
<Transition name="fade"><div v-if="cartOpen" class="overlay" @click.self="cartOpen=false"><aside><div class="asideTitle"><div><small>ВАШЕ ЗАМОВЛЕННЯ</small><h2>Кошик</h2></div><button @click="cartOpen=false">×</button></div><div v-if="!lines.length" class="empty">Кошик поки порожній<small>Додайте товари з каталогу</small></div><div v-else class="cartLines"><div v-for="x in lines" :key="x.product.id" class="cartLine"><div><b>{{x.product.name}}</b><small>{{money(x.product.price)}}</small></div><div class="quantity"><button @click="qty(x.product,-1)">−</button><span>{{x.quantity}}</span><button @click="qty(x.product,1)">+</button></div></div></div><div class="total"><span>Разом</span><b>{{money(total)}}</b></div><button class="primary" :disabled="!lines.length" @click="checkoutOpen=true;cartOpen=false">ОФОРМИТИ ЗАМОВЛЕННЯ</button></aside></div></Transition>
<Transition name="fade"><div v-if="checkoutOpen" class="overlay" @click.self="checkoutOpen=false"><form @submit.prevent="order"><div class="asideTitle"><div><small>ОСТАННІЙ КРОК</small><h2>Оформлення</h2></div><button type="button" @click="checkoutOpen=false">×</button></div><label>Ім’я та прізвище<input v-model.trim="form.customer_name" required minlength="2" maxlength="100" placeholder="Іван Петренко"></label><label>Номер телефону<input v-model.trim="form.phone" required minlength="7" maxlength="30" placeholder="+380 00 000 00 00"></label><label>Отримання<select v-model="form.delivery_method"><option value="nova_poshta">Нова пошта</option><option value="pickup">Самовивіз</option></select></label><label v-if="form.delivery_method==='nova_poshta'">Місто та відділення<input v-model.trim="form.address" required maxlength="300" placeholder="Київ, відділення №1"></label><label>Коментар<textarea v-model.trim="form.comment" maxlength="500"></textarea></label><div class="total"><span>До сплати</span><b>{{money(total)}}</b></div><p v-if="error" class="formError">{{error}}</p><button class="primary" :disabled="submitting">{{submitting?'ОФОРМЛЮЄМО…':'ПІДТВЕРДИТИ'}}</button></form></div></Transition>
<Transition name="fade"><div v-if="success" class="overlay center"><div class="success"><i>✓</i><small>ЗАМОВЛЕННЯ ПРИЙНЯТО</small><h2>Дякуємо!</h2><p>Номер замовлення</p><b>#{{success.id}}</b><p>Сума: {{money(success.total)}}</p><button class="primary" @click="success=null">ДО КАТАЛОГУ</button></div></div></Transition>
</div></template>
