<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { supabase } from './lib/supabase'

const tg=window.Telegram?.WebApp;tg?.ready();tg?.expand()
const dict={
 uk:{tag:'КОМПЛЕКТУЮЧІ · ГАРАНТІЯ · ПІДТРИМКА',hero1:'Збери ПК,',hero2:'який вражає.',heroText:'Оригінальні компоненти, чесні характеристики та допомога з підбором.',catalogLink:'ДИВИТИСЯ КАТАЛОГ ↓',original:'ОРИГІНАЛ',orders:'ЗАМОВЛЕННЯ',exchange:'ДНІВ НА ОБМІН',choose:'ОБЕРИ СВОЄ',catalog:'Каталог компонентів',products:'товарів',all:'Усі',filters:'Фільтри',manufacturer:'Виробник',allBrands:'Усі виробники',price:'Ціна',from:'Від',to:'До',stockOnly:'Тільки в наявності',sort:'Сортування',popular:'За популярністю',cheap:'Спочатку дешевші',expensive:'Спочатку дорожчі',nameSort:'За назвою',reset:'Скинути',available:'В НАЯВНОСТІ',unavailable:'НЕМАЄ',nothing:'Нічого не знайдено',changeFilters:'Спробуйте змінити фільтри',cart:'Кошик',yourOrder:'ВАШЕ ЗАМОВЛЕННЯ',empty:'Кошик поки порожній',addProducts:'Додайте товари з каталогу',total:'Разом',checkout:'ОФОРМИТИ ЗАМОВЛЕННЯ',lastStep:'ОСТАННІЙ КРОК',checkoutTitle:'Оформлення',fullName:'Ім’я та прізвище',phone:'Номер телефону',delivery:'Отримання',post:'Нова пошта',pickup:'Самовивіз',address:'Місто та відділення',comment:'Коментар',pay:'До сплати',confirm:'ПІДТВЕРДИТИ',processing:'ОФОРМЛЮЄМО…',thanks:'Дякуємо!',accepted:'ЗАМОВЛЕННЯ ПРИЙНЯТО',orderNumber:'Номер замовлення',back:'ДО КАТАЛОГУ',openTelegram:'Відкрийте магазин через Telegram-бота',loadError:'Не вдалося завантажити каталог',loading:'Завантаження…'},
 ru:{tag:'КОМПЛЕКТУЮЩИЕ · ГАРАНТИЯ · ПОДДЕРЖКА',hero1:'Собери ПК,',hero2:'который впечатляет.',heroText:'Оригинальные компоненты, честные характеристики и помощь с подбором.',catalogLink:'СМОТРЕТЬ КАТАЛОГ ↓',original:'ОРИГИНАЛ',orders:'ЗАКАЗЫ',exchange:'ДНЕЙ НА ОБМЕН',choose:'ВЫБЕРИ СВОЁ',catalog:'Каталог компонентов',products:'товаров',all:'Все',filters:'Фильтры',manufacturer:'Производитель',allBrands:'Все производители',price:'Цена',from:'От',to:'До',stockOnly:'Только в наличии',sort:'Сортировка',popular:'По популярности',cheap:'Сначала дешевле',expensive:'Сначала дороже',nameSort:'По названию',reset:'Сбросить',available:'В НАЛИЧИИ',unavailable:'НЕТ В НАЛИЧИИ',nothing:'Ничего не найдено',changeFilters:'Попробуйте изменить фильтры',cart:'Корзина',yourOrder:'ВАШ ЗАКАЗ',empty:'Корзина пока пуста',addProducts:'Добавьте товары из каталога',total:'Итого',checkout:'ОФОРМИТЬ ЗАКАЗ',lastStep:'ПОСЛЕДНИЙ ШАГ',checkoutTitle:'Оформление',fullName:'Имя и фамилия',phone:'Номер телефона',delivery:'Получение',post:'Новая почта',pickup:'Самовывоз',address:'Город и отделение',comment:'Комментарий',pay:'К оплате',confirm:'ПОДТВЕРДИТЬ',processing:'ОФОРМЛЯЕМ…',thanks:'Спасибо!',accepted:'ЗАКАЗ ПРИНЯТ',orderNumber:'Номер заказа',back:'В КАТАЛОГ',openTelegram:'Откройте магазин через Telegram-бота',loadError:'Не удалось загрузить каталог',loading:'Загрузка…'},
 en:{tag:'COMPONENTS · WARRANTY · SUPPORT',hero1:'Build a PC',hero2:'that inspires.',heroText:'Original components, honest specifications and expert selection help.',catalogLink:'VIEW CATALOG ↓',original:'ORIGINAL',orders:'ORDERS',exchange:'DAYS TO RETURN',choose:'MAKE YOUR CHOICE',catalog:'PC components',products:'products',all:'All',filters:'Filters',manufacturer:'Manufacturer',allBrands:'All manufacturers',price:'Price',from:'From',to:'To',stockOnly:'In stock only',sort:'Sort by',popular:'Popular',cheap:'Price: low to high',expensive:'Price: high to low',nameSort:'Name',reset:'Reset',available:'IN STOCK',unavailable:'OUT OF STOCK',nothing:'No products found',changeFilters:'Try changing the filters',cart:'Cart',yourOrder:'YOUR ORDER',empty:'Your cart is empty',addProducts:'Add products from the catalog',total:'Total',checkout:'CHECKOUT',lastStep:'FINAL STEP',checkoutTitle:'Checkout',fullName:'Full name',phone:'Phone number',delivery:'Delivery',post:'Nova Poshta',pickup:'Store pickup',address:'City and branch',comment:'Comment',pay:'Amount due',confirm:'CONFIRM ORDER',processing:'PROCESSING…',thanks:'Thank you!',accepted:'ORDER ACCEPTED',orderNumber:'Order number',back:'BACK TO CATALOG',openTelegram:'Open the store through the Telegram bot',loadError:'Unable to load the catalog',loading:'Loading…'}
}
const params=new URLSearchParams(location.search),initial=params.get('lang')||localStorage.getItem('ender-lang')||tg?.initDataUnsafe?.user?.language_code||'uk'
const launchToken=params.get('auth')||''
const requestedProduct=Number(params.get('product')||0)
const lang=ref(['uk','ru','en'].includes(initial)?initial:'en'),tr=computed(()=>dict[lang.value])
watch(lang,v=>{localStorage.setItem('ender-lang',v);document.documentElement.lang=v})
const products=ref([]),loading=ref(true),error=ref(''),category=ref('all'),brand=ref('all'),minPrice=ref(''),maxPrice=ref(''),stockOnly=ref(false),sort=ref('popular'),filtersOpen=ref(false)
const cart=ref(new Map(JSON.parse(localStorage.getItem('ender-cart')||'[]'))),cartOpen=ref(false),checkoutOpen=ref(false),selectedProduct=ref(null),submitting=ref(false),success=ref(null),form=ref({customer_name:'',phone:'',delivery_method:'nova_poshta',address:'',comment:''})
const detailText={uk:{details:'ХАРАКТЕРИСТИКИ',add:'ДОДАТИ В КОШИК',manufacturer:'Виробник',category:'Категорія',stock:'Наявність',units:'шт.',socket:'Сокет',cores:'Ядра',threads:'Потоки',frequency:'Частота',tdp:'TDP',warranty:'Гарантія',memory:'Відеопам’ять',memory_type:'Тип пам’яті',interface:'Інтерфейс',boost_clock:'Boost-частота',recommended_psu:'Рекомендований БЖ',capacity:'Обсяг',type:'Тип',speed:'Швидкість',modules:'Модулі',voltage:'Напруга',form_factor:'Форм-фактор',read_speed:'Швидкість читання',write_speed:'Швидкість запису',network:'Мережа',m2_slots:'Слоти M.2',power:'Потужність',efficiency:'Сертифікат',modular:'Модульність',fan:'Вентилятор',protection:'Захист'},ru:{details:'ХАРАКТЕРИСТИКИ',add:'ДОБАВИТЬ В КОРЗИНУ',manufacturer:'Производитель',category:'Категория',stock:'Наличие',units:'шт.',socket:'Сокет',cores:'Ядра',threads:'Потоки',frequency:'Частота',tdp:'TDP',warranty:'Гарантия',memory:'Видеопамять',memory_type:'Тип памяти',interface:'Интерфейс',boost_clock:'Boost-частота',recommended_psu:'Рекомендуемый БП',capacity:'Объём',type:'Тип',speed:'Скорость',modules:'Модули',voltage:'Напряжение',form_factor:'Форм-фактор',read_speed:'Скорость чтения',write_speed:'Скорость записи',network:'Сеть',m2_slots:'Слоты M.2',power:'Мощность',efficiency:'Сертификат',modular:'Модульность',fan:'Вентилятор',protection:'Защита'},en:{details:'SPECIFICATIONS',add:'ADD TO CART',manufacturer:'Manufacturer',category:'Category',stock:'Availability',units:'units',socket:'Socket',cores:'Cores',threads:'Threads',frequency:'Frequency',tdp:'TDP',warranty:'Warranty',memory:'Video memory',memory_type:'Memory type',interface:'Interface',boost_clock:'Boost clock',recommended_psu:'Recommended PSU',capacity:'Capacity',type:'Type',speed:'Speed',modules:'Modules',voltage:'Voltage',form_factor:'Form factor',read_speed:'Read speed',write_speed:'Write speed',network:'Network',m2_slots:'M.2 slots',power:'Power',efficiency:'Efficiency',modular:'Modular',fan:'Fan',protection:'Protection'}}
const details=computed(()=>detailText[lang.value])
const categoryKeys=['cpu','gpu','ram','storage','motherboard','psu'],categoryNames={uk:{cpu:'Процесори',gpu:'Відеокарти',ram:'Оперативна пам’ять',storage:'Накопичувачі',motherboard:'Материнські плати',psu:'Блоки живлення'},ru:{cpu:'Процессоры',gpu:'Видеокарты',ram:'Оперативная память',storage:'Накопители',motherboard:'Материнские платы',psu:'Блоки питания'},en:{cpu:'Processors',gpu:'Graphics cards',ram:'Memory',storage:'Storage',motherboard:'Motherboards',psu:'Power supplies'}}
const categories=computed(()=>[{key:'all',label:tr.value.all},...categoryKeys.map(key=>({key,label:categoryNames[lang.value][key]}))]),brands=computed(()=>[...new Set(products.value.filter(p=>category.value==='all'||p.category_key===category.value).map(p=>p.manufacturer))].sort())
const visible=computed(()=>{let a=products.value.filter(p=>(category.value==='all'||p.category_key===category.value)&&(brand.value==='all'||p.manufacturer===brand.value)&&(!minPrice.value||Number(p.price)>=Number(minPrice.value))&&(!maxPrice.value||Number(p.price)<=Number(maxPrice.value))&&(!stockOnly.value||p.stock>0));return [...a].sort((x,y)=>sort.value==='cheap'?x.price-y.price:sort.value==='expensive'?y.price-x.price:sort.value==='name'?productName(x).localeCompare(productName(y)):x.id-y.id)})
const productName=p=>p[`name_${lang.value}`]||p.name,productDescription=p=>p[`description_${lang.value}`]||p.description
const lines=computed(()=>[...cart.value].map(([id,quantity])=>({product:products.value.find(p=>p.id===Number(id)),quantity})).filter(x=>x.product)),count=computed(()=>lines.value.reduce((s,x)=>s+x.quantity,0)),total=computed(()=>lines.value.reduce((s,x)=>s+Number(x.product.price)*x.quantity,0)),money=v=>new Intl.NumberFormat(lang.value==='uk'?'uk-UA':lang.value==='ru'?'ru-RU':'en-US').format(Number(v))+' ₴'
function save(){localStorage.setItem('ender-cart',JSON.stringify([...cart.value]));cart.value=new Map(cart.value)}function add(p){const k=String(p.id);cart.value.set(k,Math.min((cart.value.get(k)||0)+1,p.stock));save();tg?.HapticFeedback?.impactOccurred('light')}function qty(p,d){const k=String(p.id),n=Math.min((cart.value.get(k)||0)+d,p.stock);n>0?cart.value.set(k,n):cart.value.delete(k);save()}
function resetFilters(){brand.value='all';minPrice.value='';maxPrice.value='';stockOnly.value=false;sort.value='popular'}
async function load(){loading.value=true;const r=await supabase.from('products').select('id,name,name_uk,name_ru,name_en,description,description_uk,description_ru,description_en,category_key,manufacturer,price,stock,image_url,specs').eq('active',true).order('id');loading.value=false;if(r.error)error.value=tr.value.loadError;else{products.value=r.data;if(requestedProduct&&!selectedProduct.value)selectedProduct.value=r.data.find(p=>p.id===requestedProduct)||null}}
async function order(){error.value='';if(!tg?.initData&&!launchToken&&!import.meta.env.DEV){error.value=tr.value.openTelegram;return}submitting.value=true;const payload={...form.value,items:lines.value.map(x=>({product_id:x.product.id,quantity:x.quantity}))};const r=tg?.initData?await supabase.rpc('create_telegram_order',{p_init_data:tg.initData,p_payload:payload}):await supabase.rpc('create_bot_order',{p_launch_token:launchToken,p_payload:payload});submitting.value=false;if(r.error){error.value=r.error.message;return}success.value=r.data;cart.value.clear();save();checkoutOpen.value=false;await load()}
onMounted(()=>{document.documentElement.lang=lang.value;load()})
</script>

<template><div class="app"><header><div class="brand"><i>E</i><div><b>ENDER MARKET</b><small>PC COMPONENTS</small></div></div><div class="headerActions"><div class="languages"><button v-for="code in ['uk','ru','en']" :key="code" :class="{active:lang===code}" @click="lang=code">{{code.toUpperCase()}}</button></div><button class="cartBtn" @click="cartOpen=true">🛒 <span>{{count}}</span></button></div></header>
<main><section class="hero"><div class="grid"></div><small class="overline">{{tr.tag}}</small><h1>{{tr.hero1}}<br><em>{{tr.hero2}}</em></h1><p>{{tr.heroText}}</p><a href="#catalog">{{tr.catalogLink}}</a><div class="stats"><div><b>100%</b><small>{{tr.original}}</small></div><div><b>24/7</b><small>{{tr.orders}}</small></div><div><b>14</b><small>{{tr.exchange}}</small></div></div></section>
<section id="catalog" class="catalog"><div class="sectionTitle"><div><small>{{tr.choose}}</small><h2>{{tr.catalog}}</h2></div><span>{{visible.length}} {{tr.products}}</span></div><nav class="categories"><button v-for="c in categories" :key="c.key" :class="{active:category===c.key}" @click="category=c.key;brand='all'">{{c.label}}</button></nav>
<button class="filterToggle" @click="filtersOpen=!filtersOpen">⚙ {{tr.filters}} <span>{{filtersOpen?'−':'+'}}</span></button><div class="filterPanel" :class="{open:filtersOpen}"><label>{{tr.manufacturer}}<select v-model="brand"><option value="all">{{tr.allBrands}}</option><option v-for="b in brands" :key="b" :value="b">{{b}}</option></select></label><fieldset><legend>{{tr.price}}</legend><input v-model.number="minPrice" type="number" min="0" :placeholder="tr.from"><input v-model.number="maxPrice" type="number" min="0" :placeholder="tr.to"></fieldset><label>{{tr.sort}}<select v-model="sort"><option value="popular">{{tr.popular}}</option><option value="cheap">{{tr.cheap}}</option><option value="expensive">{{tr.expensive}}</option><option value="name">{{tr.nameSort}}</option></select></label><label class="check"><input v-model="stockOnly" type="checkbox"><span>{{tr.stockOnly}}</span></label><button class="reset" @click="resetFilters">{{tr.reset}}</button></div>
<div v-if="loading" class="state">{{tr.loading}}</div><div v-else-if="!visible.length" class="state"><b>{{tr.nothing}}</b><small>{{tr.changeFilters}}</small></div><div v-else class="products"><article v-for="p in visible" :key="p.id" @click="selectedProduct=p" tabindex="0" @keydown.enter="selectedProduct=p"><div class="photo"><img :src="p.image_url" :alt="productName(p)" loading="lazy"><span>{{p.stock?tr.available:tr.unavailable}}</span></div><div class="info"><small>{{p.manufacturer}} · {{categoryNames[lang][p.category_key]}}</small><h3>{{productName(p)}}</h3><p>{{productDescription(p)}}</p><div class="price"><b>{{money(p.price)}}</b><button @click.stop="add(p)" :disabled="!p.stock">+</button></div></div></article></div></section></main>
<Transition name="fade"><div v-if="selectedProduct" class="overlay productOverlay" @click.self="selectedProduct=null"><section class="productModal"><button class="modalClose" @click="selectedProduct=null">×</button><div class="modalImage"><img :src="selectedProduct.image_url" :alt="productName(selectedProduct)"><span>{{selectedProduct.stock?tr.available:tr.unavailable}}</span></div><div class="modalBody"><small>{{selectedProduct.manufacturer}} · {{categoryNames[lang][selectedProduct.category_key]}}</small><h2>{{productName(selectedProduct)}}</h2><p>{{productDescription(selectedProduct)}}</p><div class="modalPrice">{{money(selectedProduct.price)}}</div><h3>{{details.details}}</h3><dl><div><dt>{{details.manufacturer}}</dt><dd>{{selectedProduct.manufacturer}}</dd></div><div><dt>{{details.category}}</dt><dd>{{categoryNames[lang][selectedProduct.category_key]}}</dd></div><div><dt>{{details.stock}}</dt><dd>{{selectedProduct.stock}} {{details.units}}</dd></div><div v-for="(value,key) in selectedProduct.specs" :key="key"><dt>{{details[key]||key}}</dt><dd>{{value}}</dd></div></dl><button class="primary" :disabled="!selectedProduct.stock" @click="add(selectedProduct);selectedProduct=null">{{details.add}}</button></div></section></div></Transition>
<Transition name="fade"><div v-if="cartOpen" class="overlay" @click.self="cartOpen=false"><aside><div class="asideTitle"><div><small>{{tr.yourOrder}}</small><h2>{{tr.cart}}</h2></div><button @click="cartOpen=false">×</button></div><div v-if="!lines.length" class="empty">{{tr.empty}}<small>{{tr.addProducts}}</small></div><div v-else class="cartLines"><div v-for="x in lines" :key="x.product.id" class="cartLine"><div><b>{{productName(x.product)}}</b><small>{{money(x.product.price)}}</small></div><div class="quantity"><button @click="qty(x.product,-1)">−</button><span>{{x.quantity}}</span><button @click="qty(x.product,1)">+</button></div></div></div><div class="total"><span>{{tr.total}}</span><b>{{money(total)}}</b></div><button class="primary" :disabled="!lines.length" @click="checkoutOpen=true;cartOpen=false">{{tr.checkout}}</button></aside></div></Transition>
<Transition name="fade"><div v-if="checkoutOpen" class="overlay" @click.self="checkoutOpen=false"><form @submit.prevent="order"><div class="asideTitle"><div><small>{{tr.lastStep}}</small><h2>{{tr.checkoutTitle}}</h2></div><button type="button" @click="checkoutOpen=false">×</button></div><label>{{tr.fullName}}<input v-model.trim="form.customer_name" required minlength="2" maxlength="100"></label><label>{{tr.phone}}<input v-model.trim="form.phone" required minlength="7" maxlength="30" placeholder="+380 00 000 00 00"></label><label>{{tr.delivery}}<select v-model="form.delivery_method"><option value="nova_poshta">{{tr.post}}</option><option value="pickup">{{tr.pickup}}</option></select></label><label v-if="form.delivery_method==='nova_poshta'">{{tr.address}}<input v-model.trim="form.address" required maxlength="300"></label><label>{{tr.comment}}<textarea v-model.trim="form.comment" maxlength="500"></textarea></label><div class="total"><span>{{tr.pay}}</span><b>{{money(total)}}</b></div><p v-if="error" class="formError">{{error}}</p><button class="primary" :disabled="submitting">{{submitting?tr.processing:tr.confirm}}</button></form></div></Transition>
<Transition name="fade"><div v-if="success" class="overlay center"><div class="success"><i>✓</i><small>{{tr.accepted}}</small><h2>{{tr.thanks}}</h2><p>{{tr.orderNumber}}</p><b>#{{success.id}}</b><p>{{tr.total}}: {{money(success.total)}}</p><button class="primary" @click="success=null">{{tr.back}}</button></div></div></Transition></div></template>
