create table if not exists private.admin_users (
  telegram_id bigint primary key,
  created_at timestamptz not null default now()
);
insert into private.admin_users(telegram_id) values (631516090) on conflict do nothing;

alter table public.products add column if not exists cost_price numeric(12,2) not null default 0 check (cost_price >= 0);
update public.products set cost_price=round(price*0.72,2) where cost_price=0;
alter table public.order_items add column if not exists cost_price numeric(12,2) not null default 0 check (cost_price >= 0);
update public.order_items oi set cost_price=p.cost_price from public.products p where p.id=oi.product_id and oi.cost_price=0;

create or replace function private.set_order_item_cost()
returns trigger language plpgsql security definer set search_path=public,private as $$
begin
  if new.cost_price=0 then select cost_price into new.cost_price from products where id=new.product_id; end if;
  return new;
end $$;
drop trigger if exists order_item_cost_before_insert on public.order_items;
create trigger order_item_cost_before_insert before insert on public.order_items for each row execute function private.set_order_item_cost();

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  title text not null check (length(trim(title)) between 2 and 120),
  amount numeric(12,2) not null check (amount > 0),
  expense_date date not null default current_date,
  comment text not null default '',
  created_at timestamptz not null default now()
);
alter table public.expenses enable row level security;
revoke all on public.expenses from public, anon, authenticated;

create or replace function private.require_admin(p_launch_token text)
returns bigint language plpgsql security definer
set search_path=public,private,extensions as $$
declare
  dot_pos int; encoded_payload text; received_signature text; expected_signature text;
  padded text; launch_user jsonb; token text; user_id bigint; auth_date bigint;
begin
  dot_pos:=strpos(coalesce(p_launch_token,''),'.');
  if dot_pos<2 then raise exception 'Admin authorization is missing'; end if;
  encoded_payload:=substr(p_launch_token,1,dot_pos-1);
  received_signature:=substr(p_launch_token,dot_pos+1);
  select bot_token into token from private.telegram_config where singleton=true;
  expected_signature:=encode(hmac(convert_to(encoded_payload,'UTF8'),convert_to(token,'UTF8'),'sha256'),'hex');
  if expected_signature<>received_signature then raise exception 'Invalid admin signature'; end if;
  padded:=translate(encoded_payload,'-_','+/');
  padded:=padded||repeat('=',(4-length(padded)%4)%4);
  launch_user:=convert_from(decode(padded,'base64'),'UTF8')::jsonb;
  auth_date:=coalesce((launch_user->>'auth_date')::bigint,0);
  if abs(extract(epoch from now())::bigint-auth_date)>86400 then raise exception 'Admin authorization expired'; end if;
  user_id:=(launch_user->>'id')::bigint;
  if not exists(select 1 from private.admin_users where telegram_id=user_id) then
    raise exception 'Admin access denied';
  end if;
  return user_id;
end $$;

create or replace function public.admin_get_dashboard(p_launch_token text)
returns jsonb language plpgsql security definer
set search_path=public,private,extensions as $$
declare result jsonb;
begin
  perform private.require_admin(p_launch_token);
  select jsonb_build_object(
    'metrics',jsonb_build_object(
      'revenue',coalesce((select sum(total) from orders where status<>'cancelled'),0),
      'product_cost',coalesce((select sum(oi.cost_price*oi.quantity) from order_items oi join orders o on o.id=oi.order_id where o.status<>'cancelled'),0),
      'expenses',coalesce((select sum(amount) from expenses),0),
      'orders',coalesce((select count(*) from orders),0),
      'new_orders',coalesce((select count(*) from orders where status='new'),0),
      'low_stock',coalesce((select count(*) from products where active and stock<=5),0)
    ),
    'orders',coalesce((select jsonb_agg(row_data order by created_at desc) from (
      select o.id,o.telegram_id,o.customer_name,o.phone,o.delivery_method,o.address,o.comment,o.status,o.total,o.created_at,
        coalesce((select jsonb_agg(jsonb_build_object('id',oi.id,'product_id',oi.product_id,'name',oi.product_name,'price',oi.price,'cost_price',oi.cost_price,'quantity',oi.quantity) order by oi.id) from order_items oi where oi.order_id=o.id),'[]'::jsonb) items
      from orders o
    ) row_data),'[]'::jsonb),
    'products',coalesce((select jsonb_agg(p order by p.id) from products p),'[]'::jsonb),
    'expenses_list',coalesce((select jsonb_agg(e order by e.expense_date desc,e.id desc) from expenses e),'[]'::jsonb)
  ) into result;
  return result;
end $$;

create or replace function public.admin_save_product(p_launch_token text,p_product jsonb)
returns jsonb language plpgsql security definer
set search_path=public,private,extensions as $$
declare product_id bigint; saved products%rowtype;
begin
  perform private.require_admin(p_launch_token);
  product_id:=nullif(p_product->>'id','')::bigint;
  if trim(coalesce(p_product->>'name',''))='' then raise exception 'Product name is required'; end if;
  if p_product->>'category_key' not in ('cpu','gpu','ram','storage','motherboard','psu') then raise exception 'Invalid category'; end if;
  if coalesce((p_product->>'price')::numeric,-1)<0 or coalesce((p_product->>'cost_price')::numeric,-1)<0 then raise exception 'Invalid price'; end if;
  if coalesce((p_product->>'stock')::integer,-1)<0 then raise exception 'Invalid stock'; end if;
  if product_id is null then
    insert into products(name,category,description,price,cost_price,stock,image_url,active,manufacturer,name_uk,name_ru,name_en,description_uk,description_ru,description_en,category_key,specs)
    values(trim(p_product->>'name'),p_product->>'category_key',coalesce(p_product->>'description',''),(p_product->>'price')::numeric,(p_product->>'cost_price')::numeric,(p_product->>'stock')::integer,null,coalesce((p_product->>'active')::boolean,true),trim(p_product->>'manufacturer'),coalesce(p_product->>'name_uk',p_product->>'name'),coalesce(p_product->>'name_ru',p_product->>'name'),coalesce(p_product->>'name_en',p_product->>'name'),coalesce(p_product->>'description_uk',''),coalesce(p_product->>'description_ru',''),coalesce(p_product->>'description_en',''),p_product->>'category_key',coalesce(p_product->'specs','{}'::jsonb)) returning * into saved;
  else
    update products set name=trim(p_product->>'name'),category=p_product->>'category_key',description=coalesce(p_product->>'description',''),price=(p_product->>'price')::numeric,cost_price=(p_product->>'cost_price')::numeric,stock=(p_product->>'stock')::integer,active=coalesce((p_product->>'active')::boolean,true),manufacturer=trim(p_product->>'manufacturer'),name_uk=coalesce(p_product->>'name_uk',p_product->>'name'),name_ru=coalesce(p_product->>'name_ru',p_product->>'name'),name_en=coalesce(p_product->>'name_en',p_product->>'name'),description_uk=coalesce(p_product->>'description_uk',''),description_ru=coalesce(p_product->>'description_ru',''),description_en=coalesce(p_product->>'description_en',''),category_key=p_product->>'category_key',specs=coalesce(p_product->'specs','{}'::jsonb)
    where id=product_id returning * into saved;
    if not found then raise exception 'Product not found'; end if;
  end if;
  return to_jsonb(saved);
end $$;

create or replace function public.admin_archive_product(p_launch_token text,p_product_id bigint)
returns boolean language plpgsql security definer set search_path=public,private,extensions as $$
begin
  perform private.require_admin(p_launch_token);
  update products set active=false where id=p_product_id;
  if not found then raise exception 'Product not found'; end if;
  return true;
end $$;

create or replace function public.admin_update_order_status(p_launch_token text,p_order_id bigint,p_status text)
returns boolean language plpgsql security definer set search_path=public,private,extensions as $$
begin
  perform private.require_admin(p_launch_token);
  if p_status not in ('new','confirmed','processing','shipped','completed','cancelled') then raise exception 'Invalid status'; end if;
  update orders set status=p_status where id=p_order_id;
  if not found then raise exception 'Order not found'; end if;
  return true;
end $$;

create or replace function public.admin_add_expense(p_launch_token text,p_expense jsonb)
returns jsonb language plpgsql security definer set search_path=public,private,extensions as $$
declare saved expenses%rowtype;
begin
  perform private.require_admin(p_launch_token);
  insert into expenses(title,amount,expense_date,comment) values(trim(p_expense->>'title'),(p_expense->>'amount')::numeric,coalesce((p_expense->>'expense_date')::date,current_date),coalesce(p_expense->>'comment','')) returning * into saved;
  return to_jsonb(saved);
end $$;

create or replace function public.admin_delete_expense(p_launch_token text,p_expense_id bigint)
returns boolean language plpgsql security definer set search_path=public,private,extensions as $$
begin
  perform private.require_admin(p_launch_token);
  delete from expenses where id=p_expense_id;
  if not found then raise exception 'Expense not found'; end if;
  return true;
end $$;

revoke all on function public.admin_get_dashboard(text),public.admin_save_product(text,jsonb),public.admin_archive_product(text,bigint),public.admin_update_order_status(text,bigint,text),public.admin_add_expense(text,jsonb),public.admin_delete_expense(text,bigint) from public;
grant execute on function public.admin_get_dashboard(text),public.admin_save_product(text,jsonb),public.admin_archive_product(text,bigint),public.admin_update_order_status(text,bigint,text),public.admin_add_expense(text,jsonb),public.admin_delete_expense(text,bigint) to anon,authenticated;
