create extension if not exists pgcrypto;
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists private.telegram_config (
  singleton boolean primary key default true check (singleton),
  bot_token text not null
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  description text not null default '',
  price numeric(12,2) not null check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  image_url text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create table if not exists public.customers (
  telegram_id bigint primary key,
  username text, first_name text, last_name text, phone text,
  updated_at timestamptz not null default now()
);
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null references public.customers(telegram_id),
  customer_name text not null, phone text not null,
  delivery_method text not null check (delivery_method in ('nova_poshta','pickup')),
  address text not null default '', comment text not null default '',
  status text not null default 'new',
  total numeric(12,2) not null check (total >= 0),
  created_at timestamptz not null default now()
);
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id),
  product_name text not null, price numeric(12,2) not null,
  quantity integer not null check (quantity between 1 and 20)
);
create index if not exists orders_telegram_idx on public.orders(telegram_id);
create index if not exists orders_created_idx on public.orders(created_at desc);

alter table public.products enable row level security;
alter table public.customers enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
revoke all on public.customers, public.orders, public.order_items from anon, authenticated;
grant select on public.products to anon, authenticated;
drop policy if exists "public active catalog" on public.products;
create policy "public active catalog" on public.products for select to anon, authenticated using (active = true);

create or replace function private.url_decode(value text) returns text
language plpgsql immutable strict as $$
declare result bytea = ''::bytea; i integer = 1; ch text;
begin
  value := replace(value, '+', ' ');
  while i <= length(value) loop
    ch := substr(value, i, 1);
    if ch = '%' and i + 2 <= length(value) then
      result := result || decode(substr(value, i + 1, 2), 'hex'); i := i + 3;
    else
      result := result || convert_to(ch, 'UTF8'); i := i + 1;
    end if;
  end loop;
  return convert_from(result, 'UTF8');
end $$;

create or replace function public.create_telegram_order(p_init_data text, p_payload jsonb)
returns jsonb language plpgsql security definer
set search_path = public, private, extensions as $$
declare
  pair text; pos int; key_text text; value_text text; params jsonb = '{}'::jsonb;
  received_hash text; data_check text; secret bytea; expected_hash text; token text;
  auth_date bigint; telegram_user jsonb; user_id bigint;
  item jsonb; product_row public.products%rowtype; quantity_value integer;
  total_value numeric(12,2) = 0; new_order_id bigint; seen_ids bigint[] = '{}';
begin
  if p_init_data is null or p_init_data = '' then raise exception 'Telegram authorization is missing'; end if;
  foreach pair in array regexp_split_to_array(p_init_data, '&') loop
    pos := strpos(pair, '=');
    if pos > 0 then
      key_text := private.url_decode(substr(pair,1,pos-1));
      value_text := private.url_decode(substr(pair,pos+1));
      params := params || jsonb_build_object(key_text,value_text);
    end if;
  end loop;
  received_hash := params->>'hash'; params := params - 'hash';
  if received_hash is null then raise exception 'Telegram signature is missing'; end if;
  auth_date := coalesce((params->>'auth_date')::bigint,0);
  if abs(extract(epoch from now())::bigint-auth_date)>3600 then raise exception 'Telegram authorization expired'; end if;
  select string_agg(key || '=' || value,E'\n' order by key) into data_check from jsonb_each_text(params);
  select bot_token into token from private.telegram_config where singleton=true;
  if token is null then raise exception 'Telegram bot is not configured'; end if;
  secret := hmac(convert_to(token,'UTF8'),convert_to('WebAppData','UTF8'),'sha256');
  expected_hash := encode(hmac(convert_to(data_check,'UTF8'),secret,'sha256'),'hex');
  if expected_hash <> received_hash then raise exception 'Invalid Telegram signature'; end if;
  telegram_user := (params->>'user')::jsonb; user_id := (telegram_user->>'id')::bigint;

  if jsonb_typeof(p_payload->'items') <> 'array' or jsonb_array_length(p_payload->'items') < 1 then raise exception 'Cart is empty'; end if;
  if length(trim(p_payload->>'customer_name')) not between 2 and 100 then raise exception 'Invalid customer name'; end if;
  if length(trim(p_payload->>'phone')) not between 7 and 30 then raise exception 'Invalid phone'; end if;
  if p_payload->>'delivery_method' not in ('nova_poshta','pickup') then raise exception 'Invalid delivery method'; end if;

  for item in select * from jsonb_array_elements(p_payload->'items') loop
    if (item->>'product_id')::bigint = any(seen_ids) then raise exception 'Duplicate product'; end if;
    seen_ids := array_append(seen_ids,(item->>'product_id')::bigint);
    quantity_value := (item->>'quantity')::integer;
    if quantity_value not between 1 and 20 then raise exception 'Invalid quantity'; end if;
    select * into product_row from public.products where id=(item->>'product_id')::bigint and active for update;
    if not found then raise exception 'Product is unavailable'; end if;
    if product_row.stock < quantity_value then raise exception 'Not enough stock: %',product_row.name; end if;
    total_value := total_value + product_row.price*quantity_value;
  end loop;

  insert into public.customers(telegram_id,username,first_name,last_name,phone)
  values(user_id,telegram_user->>'username',telegram_user->>'first_name',telegram_user->>'last_name',trim(p_payload->>'phone'))
  on conflict(telegram_id) do update set username=excluded.username,first_name=excluded.first_name,last_name=excluded.last_name,phone=excluded.phone,updated_at=now();
  insert into public.orders(telegram_id,customer_name,phone,delivery_method,address,comment,total)
  values(user_id,trim(p_payload->>'customer_name'),trim(p_payload->>'phone'),p_payload->>'delivery_method',coalesce(p_payload->>'address',''),coalesce(p_payload->>'comment',''),total_value)
  returning id into new_order_id;
  for item in select * from jsonb_array_elements(p_payload->'items') loop
    quantity_value := (item->>'quantity')::integer;
    select * into product_row from public.products where id=(item->>'product_id')::bigint;
    insert into public.order_items(order_id,product_id,product_name,price,quantity) values(new_order_id,product_row.id,product_row.name,product_row.price,quantity_value);
    update public.products set stock=stock-quantity_value where id=product_row.id;
  end loop;
  return jsonb_build_object('id',new_order_id,'total',total_value);
end $$;
revoke all on function public.create_telegram_order(text,jsonb) from public;
grant execute on function public.create_telegram_order(text,jsonb) to anon, authenticated;

insert into public.products(name,category,description,price,stock,image_url)
select * from (values
('AMD Ryzen 5 7600','Процесори','6 ядер / 12 потоків, AM5, до 5.1 ГГц',8499.00,12,'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=900&q=80'),
('GeForce RTX 4070 SUPER','Відеокарти','12 ГБ GDDR6X, DLSS 3, трасування променів',28999.00,5,'https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=900&q=80'),
('Kingston Fury Beast 32 ГБ','Оперативна пам’ять','DDR5-6000, комплект 2×16 ГБ',4599.00,18,'https://images.unsplash.com/photo-1562976540-1502c2145186?auto=format&fit=crop&w=900&q=80'),
('Samsung 990 EVO 1 ТБ','Накопичувачі','NVMe M.2 SSD, PCIe 4.0',3999.00,21,'https://images.unsplash.com/photo-1531492746076-161ca9bcad58?auto=format&fit=crop&w=900&q=80'),
('MSI B650 Gaming Plus WiFi','Материнські плати','AM5, DDR5, Wi-Fi 6E, ATX',7799.00,9,'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80'),
('be quiet! Pure Power 12 M 750W','Блоки живлення','80 PLUS Gold, ATX 3.0, модульний',5299.00,14,'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=900&q=80')) seed(name,category,description,price,stock,image_url)
where not exists(select 1 from public.products);
